spring.application.name: resourceater
logging.file: logs/${spring.application.name}.log
spring.output.ansi.enabled: always

management.endpoints.web.exposure.include: '*'
management.endpoint.metrics.enabled: true
