spring.application.name: resourceater
server.port: 8080

spring.output.ansi.enabled: always
spring.jackson.serialization.indent_output: true
spring.jackson.date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging.level.resourceater: DEBUG
logging.file.name: ${spring.application.home:.}/logs/${spring.application.name}.log

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles.all: 0.95, 0.98, 0.99, 0.999, 0.9999, 0.99999
management.metrics.distribution.percentiles-histogram.all: true

server.tomcat.threads.max: 100
server.tomcat.mbeanregistry.enabled: true
feign.okhttp.enabled: true

feign.client.config.containerThreadResource:
  loggerLevel: BASIC
  url: 'http://localhost:${server.port:8080}/resources/containerThreads'

feign.client.config.httpBlob:
  loggerLevel: BASIC
  url: 'http://cachefly.cachefly.net/100mb.test' # https://linhost.info/2013/10/download-test-files/
#  url: 'http://speedtest.tele2.net/100MB.zip' # http://speedtest.tele2.net/
#  url: 'http://www.ovh.net/files/100Mio.dat' # http://www.ovh.net/files/
#  url: 'choose one based on your region' # http://www.azurespeed.com/Azure/Download
