apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourceater
  labels:
    app: resourceater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourceater
  template:
    metadata:
      labels:
        app: resourceater
    spec:
      containers:
      - name: resourceater
        image: resourceater
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resourceater
  labels:
    app: resourceater
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: http
  selector:
    app: resourceater
